name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [master]
permissions:
  id-token: write
  contents: read
concurrency: production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::858777967843:role/github-actions-cdk
          aws-region: us-east-1
      - name: create api-lambda .env
        run: printf "FLICKR_API_KEY=${{ secrets.FLICKR_API_KEY }}\nFLICKR_API_SECRET=${{ secrets.FLICKR_API_SECRET }}\nGH_TOKEN=${{ secrets.GH_TOKEN }}\nSPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}\nSPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}\nLASTFM_API_KEY=${{ secrets.LASTFM_API_KEY }}\n" > api-lambda/.env
      - name: create oauth-lambda .env
        run: printf "FLICKR_API_KEY=${{ secrets.FLICKR_API_KEY }}\nFLICKR_API_SECRET=${{ secrets.FLICKR_API_SECRET }}\nSPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}\nSPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}\n" > oauth-lambda/.env
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn run check
      - run: yarn deploy
